
[en]
  languageCode = "en-us"
  contentDir = "content/en"
  title = "Print & Graphic Design @ Tallinn Estonia"
  [en.params]
    description = "Print services @ Tallinn Estonia: Business Cards, Flyers, Posters, Custom Stickers, Print on Textile; Post print: Lamination, Folding, Stapling; Vinyl Signs, Vinyl Car Wrap, Vinyl Stickers"

[et]
  languageCode = "et"
  contentDir = "content/et"
  title = "Trükk ja graafiline disain @ Tallinn Estonia"
  [et.params]
    description = "Tallinna Trükiteenused: visiitkaardid, flaierid, plakatid, kleebised, tekstiilile printimine; Pärast printimist: lamineerimine, voltimine, klammerdamine; Autode vinüülkiletamine, vinüülmärgid, vinüülkleebised"

[ru]
  languageCode = "ru"
  contentDir = "content/ru"
  title = "Печать и графический дизайн @ Таллин, Эстония"
  [ru.params]
    description = "Услуги печати в Таллине, Эстония: визитки, флаеры, плакаты, наклейки на заказ, печать на текстиле; Послепечатная обработка: ламинация, фальцовка, сшивание; Виниловые работы: Виниловые вывески, Полная обклейка автомобиля винилом, Виниловые наклейки"

